workflow:
    rules:
      - if: $CI_MERGE_REQUEST_ID
      - if: $CI_COMMIT_BRANCH == 'master'
stages:
    - build
    - test

image: php:7.2
services: 
    - mysql

building:
    artifacts:
        paths:
            - vendor/
            - .env
    stage: build
    script:
        - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose
        - apt-get update -yqq
        - apt-get install git -yqq
        - curl -sS https://getcomposer.org/installer | php
        - php composer.phar install
        - php composer.phar dump-autoload
        - chmod 777 -R storage
        - docker-php-ext-install pdo_mysql
        - cp .env.gitlab .env
        - ls .
        - php artisan key:generate
        - php artisan migrate
test:
    dependencies:
        - building
    stage: test
    script:
        - ls .
        - php artisan test

variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: seer
    MYSQL_ROOT_PASSWORD: root
    Host: mysql
    User: root
          